### PR TITLE
devel/flex: version bump to 2.6.4

### PR DESCRIPTION
**Pull request by mahaase**
fix included, that prevents segmentation fault while using flex

### CODE REVIEW

**Comment by mahaase** [comment]
wait: WIP
this flex makes me crazy, one more bug. 
seems like can be fixed with that: https://github.com/westes/flex/issues/436#issuecomment-584495742

**Comment by mahaase** [comment]
normally I would to patch the sources of flex, like e.g. archlinux does:
https://gitlab.archlinux.org/archlinux/packaging/packages/flex/-/blob/main/PKGBUILD?ref_type=heads 
but that is not possible, because autoconf isn't available while flex build.
any ideas? alternatively we could build with this flags:
```
# refer https://github.com/doxygen/doxygen/issues/8475
export CFLAGS+=" -D_GNU_SOURCE"
# refer https://github.com/westes/flex/issues/436
export ac_cv_func_malloc_0_nonnull=yes
export ac_cv_func_realloc_0_nonnull=yes
```
but no idea if that would break anything else?

**Comment by jkloetzke** [comment]
The CI failure is caused by a missing "gettext" package on the host. Instead of adding it to the prerequisites, I would refactor the recipes so that gettext is used as a tool. Then we can even remove it from the sandbox. I'll prepare an update...

**Comment by jkloetzke** [comment]
I've refactored the PR quite a bit to work around the build failure. Please have a look if it breaks anything on your side...

**Comment by mahaase** [comment]
IMO we got it finally 👍

**Comment by jkloetzke** [comment]
Great!

**Pull request merged**
