### PR TITLE
utils/xz-utils: Provide a dev package

### PR DESCRIPTION
**Pull request by Ferruck**
Upgrade to 5.2.5 whilst we're at it.

### CODE REVIEW

**Comment by Ferruck** [comment]
This probably needs some fixes in the example repos. I'll provide those if this MR is considered fine for inclusion.

**Comment by jkloetzke** [comment]
LGTM. I still need to update the example repos to the new split layout... :see_no_evil:

**Comment by Ferruck** [comment]
> I still need to update the example repos to the new split layout... :see_no_evil:

I'll do this too.

**Comment by Ferruck** [comment]
> I'll do this too.

I'll postpone the update of the examples until BobBuildTool/basement-gnu-linux#1 is merged.

**Comment by Ferruck** [comment]
I just want to follow up on this: is there anything I've missed? AFAICS, when https://github.com/BobBuildTool/basement-gnu-linux/pull/1 is merged, this and #134 can be merged, too. Afterwards, I'll update the example repos to use the latest basement including the split.

**Comment by jkloetzke** [comment]
> I just want to follow up on this: is there anything I've missed?

No. I just have been lazy... :see_no_evil:

**Pull request merged**
