### PR TITLE
cmake: autoconf host regex for windows is *-pc-* instead of *-win32

### PR DESCRIPTION
**Pull request by mahaase**
…so we also match for MSYS host environment

### CODE REVIEW

**Comment by jkloetzke** [comment]
Except from the fact that *-pc-* is way too generic I'm wondering why this is necessary. I guess you are compiling on MSYS for MSYS...

**Comment by daxcore** [comment]
`x86_64-pc-msys` is the string for native msys. vs2019 toolchain resets `AUTOCONF_HOST` than to `x86_64-pc-win32`. in both cases we got windows results, but paths must be MSYS compatible.

**Comment by jkloetzke** [comment]
Now I see. In both cases we use a native win32 cmake. Not sure if this works to build msys executables. Have you tried?

The `-pc-` is the vendor field and almost arbitrary. See https://wiki.osdev.org/Target_Triplet

**Comment by daxcore** [comment]
> Now I see. In both cases we use a native win32 cmake. Not sure if this works to build msys executables. Have you tried?

Yep, worked in my cases.

**Comment by jkloetzke** [comment]
Ok. Then we should test for `AUTOCONF_BUILD` being msys, right? Because we always use a native Cmake...

**Comment by daxcore** [comment]
indeed, would make sense!

**Comment by mahaase** [comment]
please recheck?!

**Pull request merged**
