### PR TITLE
classes/cmake: fixed argument handling of cmakeBuild function

### PR DESCRIPTION
**Pull request by mahaase**
fixes for: 
classes/cmake: not working getopts #26
classes/cmake: s option? #21

### CODE REVIEW

**Comment by jkloetzke** [comment]
Have you tested this? I've made a quick check and (as I expected) the `--` is already handled by `getopts` automatically. It will also stop parsing options as soon as the first non-option is encountered. So I think the whole patch is not necessary.

The other change in this PR is the removal of the first argument to the sources. This breaks existing recipes that use this class. I would rather make the first argument optional like the `packageScript` functions do it.

**Comment by mahaase** [comment]
for `cmakeBuild $SRCDIR -i install -m all -- -D...` the current implementation will fail like this: 

```
The "cmake -i" wizard mode is no longer supported.
Use the -D option to set cache values on the command line.
Use cmake-gui or ccmake for an interactive dialog.
```

**Comment by jkloetzke** [comment]
Yes, but you just have to switch the order of arguments. All options to `cmakeBuild` must come first, then the path to the sources and then further cmake options: `cmakeBuild -i install -m all -- $SRCDIR -D...`. You can even leave out the `--` because `getopts` will stop parsing options on the first non-option argument...

**Comment by mahaase** [comment]
thx for explanations. it was just a miss-usage, not an issue.

**Pull request closed without merging**
