### PR TITLE
bugfix python3 with openssl support

### PR DESCRIPTION
**Pull request by mahaase**
* bumped openssl to newest/last 1.1.1 version
* added `-DOPENSSL_THREADS` to `CFLAGS`

### CODE REVIEW

**Comment by jkloetzke** [comment]
I'm afraid this is not the right solution. The `OPENSSL_THREADS` define should be provided by OpenSSL headers. Could you try an update to OpenSSL 3.2.1? That should (hopefully) require no changes to python recipe.

**Comment by mahaase** [comment]
I tested 3.2.1 already. it build just fine, but however the OPENSSL_THREADS was not provided automatically. I will double check this!

**Comment by jkloetzke** [comment]
Interesting. I checked the sources yesterday and could find it. Maybe we're building OpenSSL not correctly.

**Comment by mahaase** [comment]
fixed it. added patch & bumped version. reverted python3 recipe changes.

**Comment by jkloetzke** [comment]
Thanks!

**Pull request merged**
