### PR TITLE
utils/e2fsprogs: Add initial recipe

### PR DESCRIPTION
**Pull request by Ferruck**
Also include the tools provided in the root recipe class.

### CODE REVIEW

**Comment by jkloetzke** [comment]
Could you add it to class `classes/basement/buildall.yaml` too? Then the Jenkins server will already produce an artifact...

**Comment by Ferruck** [comment]
Of course, I'll add that as soon as I get to it.

**Comment by Ferruck** [comment]
Are you still interested in these changes?

**Comment by jkloetzke** [comment]
> Are you still interested in these changes?

Sure. It doesn't hurt to have the tool around.

**Comment by Ferruck** [comment]
Feel free to merge then. :wink:

**Pull request merged**
